version: '2'

services:
  flask-api:
    build:
      context: ./flask-backend/
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./flask-backend:/simpleFlaskApp
    depends_on:
      - mongo
    user: ${CURRENT_UID}
    image: flask_backend
    container_name: flask_simple_app
    network_mode: "host"
  mongo:
    image: mongo:4.0.10
    # command: chown -R ${CURRENT_UID} /data/db
    ports:
      - "27017:27017"
    volumes:
      - ./mongoData:/data/db
      - ./dump:/dump
    container_name: mongo_simple_app
    # depends_on:
    #   - fix-mongodb-permissions
  # pixel_link:
  #   build:
  #     context: ./flask-backend/docker_models/pixel_link
  #     dockerfile: Dockerfile
  #   container_name: pixel_link_container
  #   depends_on:
  #     - mongo
  # aster:
  #   build:
  #     context: ./flask-backend/docker_models/aster
  #     dockerfile: Dockerfile
  #   container_name: aster_container
  #   depends_on:
  #     - mongo
